### PR TITLE
FLUT-6128 - [Others] Resolved the alignment issues in the filtering UG documentation

### PR DESCRIPTION
**Pull request by ashok-kuvaraja**
## Description

* We have already provided the UG documentation for our new filtering feature in flutter data grid control.
* Here, we have ensured the documentation changes in the staging site and resolved the alignment issues in the documentation.

### CODE REVIEW

**Comment by ashok-kuvaraja** [comment]
rebuil

**Comment by ashok-kuvaraja** [comment]
rebuild

**Comment by ashok-kuvaraja** [comment]
rebuild

**Review by NeelakandanKannan — APPROVED** [review]
The changes are fine.

**Comment by ashok-kuvaraja** [comment]
rebuild

**Pull request merged**
